run:
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go$"

  modules-download-mode: vendor

  build-tags:
    - dfrunsecurity
    - dfrunnetwork

linters:
  enable:
    - gofmt
    - govet
    - deadcode
    - goimports
    - ineffassign
    - misspell
    - unused
    - varcheck
    - revive
    - staticcheck
    - typecheck
    - structcheck
  disable-all: true

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
